---
- name: Install Fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Allow SSH through UFW
  ufw:
    rule: allow
    port: ssh
  notify: enable ufw

- name: Start and enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
